server:
  port: 8088
spring:
  application:
    name: microcloud-config-server-rsa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ddxx5317/spring-cloud-config-repo
          username: ddxx5317@163.com
          password: Zhaoxw2019!
   
eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ddxx:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90 
    
management: 
   security: 
     enabled: false  
     
encrypt:
  key-store:
    location: classpath:/config_server.jks     #Keystore 的文件路径
    password: ddxx2019                         #keystore 的密码
    alias: myConfigkey                         #key 的别名
    secret: ddxx2018                           #key的密码       