server:
  port: 8020
spring:
  application:
    name: microcloud-consumer-feign-hystrix-fallback-factory 
eureka:
  client: 
    service-url:
      defaultZone: http://ddxx:123456@localhost:8761/eureka/
feign:
 hystrix:
    enabled: true 