server:
  port: 8010
spring:
  application:
    name: microcloud-consumer-hystrix  
eureka:
  client: 
    service-url:
      defaultZone: http://ddxx:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90       
feign:
 hystrix:
    enabled: true 