server:
  port: 80
spring:
  application:
    name: microcloud-consumer-sleuth   
eureka:
  client: 
    service-url:
      defaultZone: http://ddxx:123456@localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG        